spring:
  application:
    name: User-Management-System

  datasource:
    url: jdbc:mysql://localhost:3306/umsdb?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

myapp:
  jwt:
    secret: hGelQXbjl1Age5+yS/KEii9MXSYpbyWWelUfwoHtOSY=
    access_expiry: 5
    refresh_expiry: 1440
